name: znn_swap_utility
description: Zenon Swap utility
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  hex: ^0.2.0
  pointycastle: ^3.3.4
  path: ^1.8.0
  crypto: ^3.0.1
  sprintf: ^6.0.0
  ffi: ^1.1.2
  aes_crypt_null_safe: ^2.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.18.2
  dart_code_metrics: ^4.3.3
